---
dist: bionic
language: ruby
cache: bundler
before_install:
  - yes | gem update --system
  - bundle --version
  - git clone https://github.com/puppetlabs/puppetlabs-ruby_task_helper ../ruby_task_helper
  - scripts/start-gitlab.sh
script:
  - 'bundle exec rake $CHECK'
matrix:
  fast_finish: true
  include:
  - rvm: 2.4.4
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=test
  - rvm: 2.5.3
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 6.0" CHECK=test_with_coveralls
  - rvm: 2.5.3
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 6.0" CHECK=rubocop
  - rvm: 2.4.4
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=build DEPLOY_TO_FORGE=yes
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=centos6-64 CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=centos6-64 CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=centos7-64 CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=centos7-64 CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=centos8-64 CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=centos8-64 CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=debian8-64 CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=debian8-64 CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=debian9-64 CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=debian9-64 CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=debian10-64 CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=debian10-64 CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=ubuntu1604-64 CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=ubuntu1604-64 CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=ubuntu1804-64 CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=ubuntu1804-64 CHECK=beaker
    services: docker
branches:
  only:
  - master
  - /^v\d/
notifications:
  email: false
  webhooks: https://voxpupu.li/incoming/travis
  irc:
    on_success: always
    on_failure: always
    channels:
      - "chat.freenode.org#voxpupuli-notifications"
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: "uwKQeb0ngonWkgYCFTgrzALAOhjlTBXmJMTdB37z/E9cdFRqwDJy6aUpgXTMCareaiEUaKnkPW0+nNRZZl+ewA7JOb1oBqx2rYNf1URX+eRQLT5yZjD+9h2r1pSNId3ku45q4WhtWRsZ/foD3iPM+S 2g2BI28Ui4/AZYvz//YBa9uWpxVb1pqr2x6aAWxfh3pIGAiok8YnsYZ3qoW0MheGAcL4ReLsdQD9+eSUHYx+eA0zHvMbBVpdTnwFbEgD0WLV5bhaNShHBYWLrOKrYZFsd+XZjOyC8jDiYReeo219KHjDd5RZL38FC8Mtg+oHjUKUvvq2GEKDpPGq1BJ3opBChYbPfRx4KVQpYBeYap9PtkE2s9rSbvsARYVELl9nVoW0j2+nZYhL94efXieEiX/Qt/rwyR9YFvuRO71hzA4nIIaC11pz+kLm1uzJsLgd5tVAlUQjhjvUecRdL98XoI0WTGm3l4sT/ptqfdRvP4XJj0jN4twEQ6FKKUAQ0oaPOZwM2HF4YRN9PtijqU1VoZsUEpYtJECGQjrWEADpYD4qpRxpgGw/4/k/McRFegLC1oCSNqB2uiZIqyTmcr9X5ycNkG0yis4Koq+Chc4CXgZTOAwa2AgzUI8qPdBTI/1G1CBSiGta1X5MKHQM2yEgj2G0jnDAFhi5Im1ylYjBb5O+k="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish the build marked with "DEPLOY_TO_FORGE"
    condition: "$DEPLOY_TO_FORGE = yes"
