---
# (NOT) Managed by modulesync???
# https://voxpupuli.org/docs/updating-files-managed-with-modulesync/

name: CI

on: pull_request

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  setup_matrix:
    name: 'Setup Test Matrix'
    runs-on: ubuntu-latest
    timeout-minutes: 40
    outputs:
      puppet_unit_test_matrix: ${{ steps.get-outputs.outputs.puppet_unit_test_matrix }}
      puppet_beaker_test_matrix: ${{ steps.get-outputs.outputs.puppet_beaker_test_matrix }}
    env:
      BUNDLE_WITHOUT: development:system_tests:release
      PUPPET_GEM_VERSION: ">= 7.0"
    steps:
      - uses: actions/checkout@v4
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: Run static validations
        run: bundle exec rake validate lint check
      - name: Run rake rubocop
        run: bundle exec rake rubocop
      - name: Setup Test Matrix
        id: get-outputs
        run: bundle exec metadata2gha

  unit:
    needs: setup_matrix
    runs-on: ubuntu-latest
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        include: ${{fromJson(needs.setup_matrix.outputs.puppet_unit_test_matrix)}}
    env:
      BUNDLE_WITHOUT: development:system_tests:release
      PUPPET_VERSION: "~> ${{ matrix.puppet }}.0"
    name: Puppet ${{ matrix.puppet }} (Ruby ${{ matrix.ruby }})
    steps:
      - uses: actions/checkout@v4
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Create task helper symlink
        run: ln -s puppet-gitlab_ci_runner/spec/fixtures/modules/ruby_task_helper ../
      - name: Run tests
        run: bundle exec rake parallel_spec

  acceptance:
    needs: setup_matrix
    runs-on: ubuntu-24.04
    env:
      BUNDLE_WITHOUT: development:test:release
    strategy:
      fail-fast: false
      matrix:
        include: ${{fromJson(needs.setup_matrix.outputs.puppet_beaker_test_matrix)}}
    name: "${{ matrix.name }}"
    steps:
      - uses: actions/checkout@v4
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: Start gitlab
        run: ./scripts/start-gitlab.sh
      - name: Start squid
        run: ./scripts/start-squid.sh
      - name: Run tests
        run: bundle exec rake beaker
        env: ${{ matrix.env }}
      - name: squid logs
        run: docker logs squid --tail 50
        if: always()


  tests:
    needs:
      - unit
      - acceptance
    runs-on: ubuntu-latest
    name: Test suite
    steps:
      - run: echo Test suite completed
